make_dataset:
  split_data: 0
  split_ratio: 0.2
  seed: 17
  
# prepare:
prepare:
  benchmark: 20
  train_test: 'train' #test
  resize: [128, 128]
  color_mode: "Gray" #Gray YCbCr RGB
  normalize: False
  filter: 
    method: "gaussian" #sobel gaussian gabor 
    gaussian: 
      kernel: [5, 5]
      sigma: 0.5
    gabor:
      sigma: 5
      frequency: 0.6
  feature_extract:
    method: "pca" #fft sift hog ela lbp apply_landmark_detection
    pca:
      components: 1
    ela:
      quality: 70
    lbp:
      radius: 1
      n_points: 8




train:
  train: False
  model_benchmark: 1
  model: "svm" 
  split_ratio: 0.2
  scale_features: "standard" #standard
  params: True
  svm:
    C: [0.1, 1, 10]
    gamma: ['auto'] #'scale', 
    kernel: ['linear', 'rbf', 'poly']
  knn:
    n_neighbors: [3, 5, 7, 10]
    weights: ['uniform', 'distance']
  rf:
    n_estimators: [50, 100, 200]
    max_depth: [None, 10, 20]
    min_samples_split: [2, 5, 10]
  lgbm:
    n_estimators: [100, 200]
    learning_rate: [0.01, 0.1, 0.2]
  xgb:
    n_estimators: [100, 200]
    learning_rate: [0.01, 0.1, 0.2]

# evaluate:
